### ISSUE TITLE
Design Refactoring

### ISSUE THREAD

**Issue by HarGarX** [creaspo23/SolaJobs#1]
Please Consider editing the design of the whole projects with pohots and form as we agreed on the whatsapp  due Tuesday :-
1.  **_https://www.google.com/imgres?imgurl=https%3A%2F%2Fimg.etimg.com%2Fthumb%2Fwidth-640%2Cheight-480%2Cimgsize-145951%2Cresizemode-1%2Cmsid-55062562%2Fsmall-biz%2Fstartups%2Fwomen-focused-recruitment-cos-are-helping-women-find-work-after-a-career-break.jpg&imgrefurl=https%3A%2F%2Fm.economictimes.com%2Fsmall-biz%2Fstartups%2Fwomen-focused-recruitment-cos-are-helping-women-find-work-after-a-career-break%2Farticleshow%2F55062365.cms&tbnid=4NVA3HZiqzB8WM&vet=12ahUKEwjXuIP-nv_tAhXPOuwKHdyABnYQMygVegUIARDaAQ..i&docid=-jQmlkQbhAwdtM&w=640&h=480&q=recruitment%20photos%20female&client=ubuntu&ved=2ahUKEwjXuIP-nv_tAhXPOuwKHdyABnYQMygVegUIARDaAQ_**
2. **_https://news.blr.com/app/uploads/sites/3/2017/11/Petersen.jpg_**
3. **_https://madsourcer.com/wp-content/uploads/home-top-background-mobile.jpg_**
4. **_https://jeroenkraaijenbrink.com/wp-content/uploads/2020/01/jumpstarting-2020-five-simple-tips-for-more-effective-meetings-960x480.jpg_**
5. **_https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.psdgroup.com%2Fbalance-for-better-diversity-matters%2F&psig=AOvVaw3bmB9DNdCkeF0kAGLih3-Q&ust=1609745430292000&source=images&cd=vfe&ved=2ahUKEwjcjNeVn__tAhXOtKQKHb1RCl8QjRx6BAgAEAc_**

**Comment by wali-eldin-hassan** [comment]
f*** my life
